### ISSUE TITLE
[FEATURE] update the video guide for v11

### ISSUE THREAD

**Issue by Rubengam3r** [League-of-Foundry-Developers/scene-packer#126]
**Is your feature request related to a problem? Please describe.**
Compendium folders is now part of core foundry.
When exporting scenes I get an error because of generatingThumbnail.

**Describe the solution you'd like**
 A walkthrough guide for foundry v11

**Describe alternatives you've considered**

**Additional context**

**Comment by sneat** [comment]
Hi @Rubengam3r - I'll address your 3 parts separately.

1. `Compendium folders is now part of core foundry` - It is, so you don't have to use the Compendium Folders module if you don't want. Scene Packer supports version prior to v11 though, so functionality will remain though. Are you having any troubles with the folders? My test today had folders working correctly using the core functionality in v11.
2. `When exporting scenes I get an error because of generatingThumbnail` - Can you show me what error you get? I didn't get any errors when I testing locally, so I assume the flow I did was different to you. Keen to see how to trigger the error.
3. `A walkthrough guide for foundry v11` - I'll try to make an updated video for v11, but the steps are essentially the same. Is there a part of the existing walkthrough that is now wrong?

Feel free to jump on the discord server (link in the readme) if you think you'd find it easier to talk through there.

**Comment by Rubengam3r** [comment]
Thanks for the response.
1. I wasn't sure if the functionality was any different. So I will go through it again and see if I get a different result.
2.  When I hit Export Content I get the error. The only way around it is to do the Keep Document  IDs. which from following the guide didn't seem like the right thing to do.
![Screenshot 2023-06-19 081110](https://github.com/League-of-Foundry-Developers/scene-packer/assets/32652791/61140966-3998-40b1-8ee4-d78be220ba5b)
![Screenshot 2023-06-19 081203](https://github.com/League-of-Foundry-Developers/scene-packer/assets/32652791/d5d12e9b-d500-4d76-896c-eac3d98c096f)

3. If you do great, If not I understand. It very well could be that I am doing the process wrong. I will try again and reach out to discord if I have any furthur issues. Thanks

**Comment by sneat** [comment]
You've found a bug with the core system @Rubengam3r ! The bug report is here https://github.com/foundryvtt/foundryvtt/issues/9645 and it's scheduled to be fixed in the next v11 version.

But to work around it, tick the `Keep Document IDs` and `Merge By Name` fields. You can tick the `Keep Folder Structure` if you have folders as well.

Some historical context: Back in v8 days, it made some sense to not keep the document IDs (a lot of Foundry was based on the IDs changing). Thesedays, a lot of Foundry is based on the IDs being able to stay the same, so you can tick the `Keep Document IDs` all the time.
