### ISSUE TITLE
[BUG] Report Macro has no error handling

### ISSUE THREAD

**Issue by arcanistzed** [League-of-Foundry-Developers/scene-packer#17]
**Describe the bug**
There is no error handling for when someone runs the performance report macro in a world with no modules initialized with Scene Packer.

**Versions (please complete the following information):**
 - FoundryVTT Core: 0.8.2
 - System: 1.3.0
 - Scene Packer Version: 2.1.1

**To Reproduce**
1. Open a world with no modules initialized with Scene Packer
2. Import the macros from the compendium
3. Run the Report macro

**Expected behavior**
I expected a notification similar to the one that is displayed for the relinking macro

**Screenshots**
![image](https://user-images.githubusercontent.com/82790112/117555093-3046e680-b02a-11eb-9232-4c1c881c0945.png)

**Comment by sneat** [comment]
@arcanistzed Were you doing this on a world that didn't have a real scene in it? The report macro actually has nothing to do with Scene Packer other than it being bundled with it.

The error you're hitting there is to do with not being able to find the `tiles` layer on the canvas, but that shouldn't happen given you were fine getting the `walls` and `tokens` layers etc.

I'll push a fix so that it at least doesn't error (and reports 0), but I'd like to investigate this more with you to work out why you don't have a tiles layer.

**Comment by waterlava** [comment]
Yes, I believe that happened when I tried running it with no scenes

**Comment by arcanistzed** [comment]
Yes, I believe I got that error when I tried running it on a world with no scenes

**Comment by sneat** [comment]
Running it on a world that doesn't have a scene gives me this (after modifying some code):

```
Core:
  Foundry: 0.8.3
  System: dnd5e version 1.3.1
User:
  Role: GAMEMASTER
Scene:
  Name: undefined
  Walls: 0
  Lights: 0
  Tokens: 0
  Tiles: undefined
  Sounds: 0
  Drawings: 0
  Notes: 0
  Dimensions: undefined x undefined
  Background: undefined x undefined
```

Whereas it errors otherwise - although it's erroring that there's no Scene name for me.

Regardless, v2.2.1 should fix the issue you're seeing. Let me know if it doesn't.
